openapi: 3.0.1
info:
  title: Servicio de pagos
  description: Contiene los servicos expuestos al usuario final para realizar el pago y compensación
  version: 1.0.0
servers:
  - url: 'https://localhost:8080/Pagar'
paths:
  /api/pay:
    post:
      summary: Servicio que permite la realización de un pago.
      description: Recibe la información de usuario, convenio, referencia y valor a pagar, y direcciona el pago al convenio correspondiente.
      requestBody:
        description: Datos para el pago.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PagoRequest'
      responses:
        '200':
          description: Operación exitosa, ver mensaje con el resultado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '400':
          description: Bad request, hay algún error en los parámetros especificados
        '404':
          description: Número de factura no encontrado
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    PagoRequest:
      type: object
      properties:
        idUsuario:
          type: integer
          description: Identificador del usuario que realiza el pago.
        idConvenio:
          type: integer
          description: Código del convenio al cual se va a realizar el pago
        referencia:
          type: integer
          description: Número de referencia de recaudo o número de factura
        valor:
          type: integer
          description: Valor a pagar o compensar.
    PaymentResponse:
      type: object
      properties:
        referencia:
          type: integer
        mensaje:
          type: string
        nroTransaccion:
          type: string
    UsuarioObject:
      type: object
      properties:
        idUsuario:
          type: integer
        nombre:
          type: string
        email:
          type: string
      required:
        - nombre
        - email
