openapi: 3.0.3
info:
  title: 'Servicio de Gestión de usuarios'
  version: '1.0'
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licences/LICENSE-2.0.html"
  contact:
      name: "Byron Martínez, Edgar Javier Rivera, Rafael Ocampo"
      email: "ejriveram@javeriana.edu.co"
servers:
  - url: 'https://localhost:8080/usuarios'
    description: Servidor que contiene los servicios de gestión de usuarios
paths:
  /api/{idUsuario}:
    get:
      description: Permite consultar la informació del usuario con el id recibido como parámetro
      parameters:
        - in: path
          name: idUsuario
          schema:
            type: integer
          description: Identificador del usuario que se desea consultar
          required: true   
      responses:
        '200':
          description: Consulta de usaurio exitosa, usuario encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioObject'
        '404':
          description: No se encontró un registro de usuario con ese Id
    delete:
      description: Permite inactivar un usuario
      parameters:
        - in: path
          name: idUsuario
          schema:
            type: integer
          description: Identificador del usuario que se desea consultar
          required: true
      responses:
          '200':
            description: Usuario eliminado
          '404':
            description: No se encontró un registro de usuario con ese Id

  /api:
    post:
      description: Permite crear un registro de un usuario
      requestBody:
        description: Contiene los datos del usuario que se desea crear
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/UsuarioObject'
      responses:
        '200':
          description: Usuario creado exitosamente
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/UsuarioObject'
        '400':
          description: Los parametros recibidos no permiten registrar el usuario
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioObject'

    put:
      description: Permite Actualizar la información de un usuario
      requestBody:
        description: Contiene los datos del usuario que se desea crear
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/UsuarioObject'
      responses:
        '200':
          description: Usuario creado exitosamente
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/UsuarioObject'
        '400':
          description: Los parametros recibidos no permiten actualizar la información el usuario
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: El usuario que se quiere actualizar no existe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    UsuarioObject:
      type: object
      properties:
        idUsuario:
          type: integer
        nombre:
          type: string
        email:
          type: string
      required:
        - nombre
        - email
