apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{.Values.ingress.name}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: {{.Values.ingress.path}}/$2
  namespace: default
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: {{.Values.service.name}}
              servicePort: {{ .Values.service.portcluster }}
            path: {{.Values.ingress.path}}(/|$)(.*)