apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.container.port }}
      targetPort: {{.Values.service.portcluster}}